In [3]:
import numpy as np

In [4]:
print(np.__version__)
np.show_config()

1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib'

In [5]:
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
Z=np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [9]:
np.info(np.add) #前面numpy已经as成np,所以这里就不用numpy而是用np。

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [12]:
Z=np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
Z=np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [15]:
Z=np.arange(50)
Z=Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [16]:
Z=np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [18]:
Z=np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
Z=np.random.random((3,3,3))
print(Z)

[[[7.56258277e-01 5.82838729e-01 4.19700368e-02]
  [1.36089474e-01 4.68282558e-02 1.96628733e-02]
  [7.20471864e-01 5.78619977e-01 6.49164909e-01]]

 [[5.86781220e-02 5.27479752e-01 8.24110879e-01]
  [9.64277265e-01 6.28244821e-01 5.26130469e-01]
  [6.21239888e-04 5.32684485e-01 7.61708349e-01]]

 [[1.29229085e-01 4.56385210e-01 1.95524116e-02]
  [2.36420405e-01 2.45230961e-01 5.29467093e-01]
  [4.55175654e-01 2.68330132e-01 5.44832982e-01]]]


In [20]:
Z=np.random.random((10,10))
Zmin, Zmax, = Z.min(), Z.max()
print(Zmin, Zmax)

0.004710498468077584 0.996800601863515


In [24]:
Z=np.random.random(30)
m=Z.mean()
print(m)

0.5547203591971572


In [26]:
Z=np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [28]:
Z=np.ones((5,5))
Z=np.pad(Z, pad_width = 1, mode = 'constant', constant_values = 0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [35]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(0.3 != 3 * 0.1)

nan
False
False
True


In [36]:
Z=np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [37]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [38]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [39]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [40]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.71036336 0.35770312 1.         0.73615504 0.72581981]
 [0.74259259 0.62712422 0.47417013 0.28547754 0.08584138]
 [0.19804331 0.         0.37870382 0.6101473  0.16791132]
 [0.84767763 0.4763945  0.59178885 0.95618255 0.8108152 ]
 [0.64662145 0.07092779 0.34836151 0.97198394 0.5562807 ]]


In [41]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [42]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [43]:
Z=np.arange(11)
Z[(Z>3)&(Z<=8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [44]:
print(sum(range(5),-1))

9


In [45]:
from numpy import *
print(sum(range(5),-1))

10


In [49]:
Z = np.arange(5)
Z ** Z  # legal

array([  1,   1,   4,  27, 256], dtype=int32)

In [55]:
Z = np.arange(5)
2 << Z >> 2  # false

array([0, 1, 2, 4, 8], dtype=int32)

In [51]:
Z = np.arange(5)
Z <- Z   # legal

array([False, False, False, False, False])

In [52]:
Z = np.arange(5)
1j*Z   # legal

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [53]:
Z = np.arange(5)
Z/1/1   # legal

array([0., 1., 2., 3., 4.])

In [54]:
Z = np.arange(5)
Z<Z>Z    # false

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [56]:
print(np.array(0) / np.array(0))

nan


D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [57]:
print(np.array(0) // np.array(0))

0


D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [58]:
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


In [59]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ -3.  -2.   2.   7.  -8. -10.  -8.   7.   9.   5.]


In [63]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))#找到两个数组中的共同元素

[0 4 6 7 8 9]


In [71]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [74]:
# Back to sanity
_ = np.seterr(**defaults)

#An equivalent way, with a context manager:
    
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

In [75]:
np.sqrt(-1) == np.emath.sqrt(-1)  # False,虚数

False

In [76]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-20
Today is 2019-06-21
Tomorrow is 2019-06-22


In [77]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [78]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B) #A+B

array([3., 3., 3.])

In [79]:
np.divide(A,2,out=A) #A/2

array([0.5, 0.5, 0.5])

In [80]:
np.negative(A,out=A)#A取负数

array([-0.5, -0.5, -0.5])

In [81]:
np.multiply(A,B,out=A)#A*B

array([-1.5, -1.5, -1.5])

In [83]:
 Z = np.random.uniform(0,10,10)#五种方法提取一个随机数组的整数部分

print (Z - Z%1)

[0. 3. 1. 0. 5. 1. 1. 6. 9. 8.]


In [84]:
print (np.floor(Z))

[0. 3. 1. 0. 5. 1. 1. 6. 9. 8.]


In [85]:
print (np.ceil(Z)-1)

[0. 3. 1. 0. 5. 1. 1. 6. 9. 8.]


In [86]:
print (Z.astype(int)) #后面的点去掉了

[0 3 1 0 5 1 1 6 9 8]


In [87]:
print (np.trunc(Z))

[0. 3. 1. 0. 5. 1. 1. 6. 9. 8.]


In [88]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [91]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [94]:
Z = np.linspace(0,1,11,endpoint=False)[1:] #创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [95]:
Z=np.random.random(10) #创建一个长度为10的随机向量，并将其排序
Z.sort()
print (Z)

[0.03180276 0.03828618 0.10418554 0.22500851 0.29328059 0.42542323
 0.49324825 0.64935329 0.83413884 0.94092062]


In [96]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [101]:
A = np.random.randint(0,2,5) # 对于两个随机数组A和B，检查它们是否相等
B = np.random.randint(0,2,5) 
#equal = np.allclose(A,B)
equal = np.array_equal(A,B)
print(equal)

False


In [102]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [106]:
Z = np.random.random((10,2)) #44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.29781289 1.05349029 0.49546074 1.10163071 0.77280182 1.03218352
 1.03181217 1.28518697 0.18450259 1.08867473]
[0.82891446 0.71531824 1.17019883 0.7983931  1.24798833 0.8531541
 0.54666149 0.76836536 1.20894243 0.53722589]


In [110]:
Z = np.random.random(10) #45. 创建一个长度为10的向量，并将向量中最大值替换为1
Z[Z.argmax()] = 0
print(Z)

[0.00207436 0.76630013 0.18628319 0.52846472 0.17112355 0.22752644
 0.35796831 0.         0.45458192 0.810938  ]


In [111]:
Z = np.zeros((5,5), [('x',float),('y',float)]) #46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                            np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [118]:
X = np.arange(8) #??? 47.构造Cauchy矩阵C (Cij =1/(xi - yj)),构建成功了吗
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [120]:
for dtype in [np.int8, np.int32, np.int64]: #48. 打印每个numpy标量类型的最小值和最大值
    print(np.iinfo(dtype).min) 
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [131]:
np.set_printoptions(threshold=1) #49为什么threshold must be numeric and non-NAN？threshold换成数字才可以。
Z = np.zeros((16,16))
print (Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [132]:
Z = np.arange(100) #50. 给定标量时，如何找到数组中最接近标量的值？
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

65


In [133]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1), #51. 创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ... ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [134]:
Z = np.random.random((10,2)) #52. 对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[0.         0.29740177 0.82225045 ... 0.52965417 0.43087449 0.60891596]
 [0.29740177 0.         1.09970501 ... 0.70971156 0.16469624 0.89140674]
 [0.82225045 1.09970501 0.         ... 0.53903272 1.1849456  0.21535612]
 ...
 [0.52965417 0.70971156 0.53903272 ... 0.         0.73760772 0.41924805]
 [0.43087449 0.16469624 1.1849456  ... 0.73760772 0.         0.98578123]
 [0.60891596 0.89140674 0.21535612 ... 0.41924805 0.98578123 0.        ]]


In [135]:
# # 方法2
# # Much faster with scipy
import scipy
# # Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial
D = scipy.spatial.distance.cdist(Z,Z)
print (D)

[[0.         0.29740177 0.82225045 ... 0.52965417 0.43087449 0.60891596]
 [0.29740177 0.         1.09970501 ... 0.70971156 0.16469624 0.89140674]
 [0.82225045 1.09970501 0.         ... 0.53903272 1.1849456  0.21535612]
 ...
 [0.52965417 0.70971156 0.53903272 ... 0.         0.73760772 0.41924805]
 [0.43087449 0.16469624 1.1849456  ... 0.73760772 0.         0.98578123]
 [0.60891596 0.89140674 0.21535612 ... 0.41924805 0.98578123 0.        ]]


In [137]:
Z = np.arange(10, dtype=np.int32) #将32位的浮点数(float)转换为对应的整数(integer)
Z = Z.astype(np.float32, copy=False)
print (Z)

[0. 1. 2. ... 7. 8. 9.]


In [138]:
Z = np.arange(9).reshape(3,3) #枚举。55、对于numpy数组，enumerate的等价操作
for index, value in np.ndenumerate(Z):
   print (index, value)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [139]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10)) #56. 生成一个通用的二维Gaussian-like数组
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 ...
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]]


In [144]:
n = 5 #57. 对一个二维数组，如何在其内部随机放置p个元素?
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [146]:
X = np.random.rand(5, 10) #58. 减去一个矩阵中的每一行的平均值
# # Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.06710795 -0.29135948  0.31109006 ... -0.36934687  0.19916892
   0.14928427]
 [ 0.25137427  0.31998427  0.33239635 ... -0.24093569  0.11275656
  -0.00382238]
 [-0.3131917   0.06994293 -0.12300786 ...  0.53962805 -0.18550482
   0.50026651]
 [ 0.35612418 -0.29208284  0.322591   ...  0.29394496 -0.14081465
  -0.39231496]
 [ 0.13777747 -0.13935867  0.11388003 ...  0.26543261 -0.44351913
   0.16392269]]
[[ 0.06710795 -0.29135948  0.31109006 ... -0.36934687  0.19916892
   0.14928427]
 [ 0.25137427  0.31998427  0.33239635 ... -0.24093569  0.11275656
  -0.00382238]
 [-0.3131917   0.06994293 -0.12300786 ...  0.53962805 -0.18550482
   0.50026651]
 [ 0.35612418 -0.29208284  0.322591   ...  0.29394496 -0.14081465
  -0.39231496]
 [ 0.13777747 -0.13935867  0.11388003 ...  0.26543261 -0.44351913
   0.16392269]]


In [147]:
# # 方法2
# # Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)
print (Y)

[[ 0.06710795 -0.29135948  0.31109006 ... -0.36934687  0.19916892
   0.14928427]
 [ 0.25137427  0.31998427  0.33239635 ... -0.24093569  0.11275656
  -0.00382238]
 [-0.3131917   0.06994293 -0.12300786 ...  0.53962805 -0.18550482
   0.50026651]
 [ 0.35612418 -0.29208284  0.322591   ...  0.29394496 -0.14081465
  -0.39231496]
 [ 0.13777747 -0.13935867  0.11388003 ...  0.26543261 -0.44351913
   0.16392269]]


In [3]:
import numpy as np #59. 如何通过第n列对一个数组进行排序?
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,0].argsort()])

[[4 5 0]
 [1 4 2]
 [0 7 3]]
[[0 7 3]
 [1 4 2]
 [4 5 0]]


In [4]:
Z = np.random.randint(0,3,(3,10)) #60. 如何检查一个二维数组是否有空列？
print ((~Z.any(axis=0)).any())

True


In [5]:
Z = np.random.uniform(0,1,10) #61. 从数组中的给定值中找出最近的值 
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.5251998133168997


In [6]:
A = np.arange(3).reshape(3,1) #62. 如何用迭代器(iterator)计算两个分别具有形状(1,3)和(3,1)的数组?
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [7]:
class NamedArray(np.ndarray): #（再看）63. 创建一个具有name属性的数组类
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [12]:
Z = np.ones(10) #（有难度！！！）64. 考虑一个给定的向量，如何对由第二个向量索引的每个元素加1(小心重复的索引)?
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 4. 3. 4. 2. 4. 4. 2. 2. 2.]


In [18]:
# # 方法2
np.add.at(Z, I, 1)
print(Z)

[13. 19. 13. 19.  7. 19. 19.  7.  7.  7.]


In [19]:
X = [1,2,3,4,5,6] #65. 根据索引列表(I)，如何将向量(X)的元素累加到数组(F)?
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [21]:
w,h = 16,16 #66. 考虑一个(dtype=ubyte) 的 (w,h,3)图像，计算其唯一颜色的数量
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte) 
# #Note that we should compute 256*256 first. 
# #Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


In [22]:
A = np.random.randint(0,10,(3,4,3,4)) #67. 考虑一个四维数组，如何一次性计算出最后两个轴(axis)的和？
# # solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print (sum)

[[50 56 53 49]
 [42 50 58 57]
 [44 51 65 51]]


In [23]:
# # 方法2
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print (sum)

[[50 56 53 49]
 [42 50 58 57]
 [44 51 65 51]]


In [24]:
D = np.random.uniform(0,1,100) #68. 考虑一个一维向量D，如何使用相同大小的向量S来计算D子集的均值？
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)

[0.39598072 0.31095465 0.50924856 0.39710371 0.28940303 0.40746553
 0.42750716 0.56812746 0.51911154 0.5383431 ]


In [25]:
# # 方法2
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.395981
1    0.310955
2    0.509249
3    0.397104
4    0.289403
5    0.407466
6    0.427507
7    0.568127
8    0.519112
9    0.538343
dtype: float64


In [28]:
A = np.random.uniform(0,1,(5,5)) #69. 如何获得点积 dot prodcut的对角线?
B = np.random.uniform(0,1,(5,5))
# # slow version
np.diag(np.dot(A, B))

## 方法2
# # Fast version
np.sum(A * B.T, axis=1)

array([0.78542674, 2.70956547, 0.88696658, 0.64639284, 1.20918784])

In [29]:
## 方法3
# # Faster version
np.einsum("ij,ji->i", A, B)

array([0.78542674, 2.70956547, 0.88696658, 0.64639284, 1.20918784])

In [30]:
Z = np.array([1,2,3,4,5]) #70. 考虑一个向量[1,2,3,4,5],如何建立一个新的向量，在这个新向量中每个值之间有3个连续的零？
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [31]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print (A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [32]:
A = np.arange(25).reshape(5,5) #72. 如何对一个数组中任意两行做交换?
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [33]:
faces = np.random.randint(0,100,(10,3)) #（有难度！！！）73. 考虑一个可以描述10个三角形的triplets，找到可以分割全部三角形的line segment
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 0,  9) ( 7, 17) ( 7, 79) ( 8, 33) ( 8, 51) ( 9,  9) (11, 25) (11, 90)
 (15, 54) (15, 63) (17, 79) (18, 48) (18, 69) (23, 51) (23, 99) (25, 90)
 (33, 47) (33, 51) (33, 65) (39, 44) (39, 78) (44, 78) (47, 65) (48, 69)
 (49, 66) (49, 69) (51, 99) (54, 63) (66, 69)]


In [34]:
C = np.bincount([1,1,2,3,4,4,6]) #74. 给定一个二进制的数组C，如何产生一个数组A满足np.bincount(A)==C(★★★)
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


In [35]:
def moving_average(a, n=3) : #75. 如何通过滑动窗口计算一个数组的平均数? (★★★)
(提示: np.cumsum)
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [40]:
from numpy.lib import stride_tricks 
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [42]:
Z = np.random.randint(0,2,100) #77. 如何对布尔值取反，或者原位(in-place)改变浮点数的符号(sign)？(★★★)
np.logical_not(Z, out=Z)

array([0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1])

In [43]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.23390331, -0.48455722, -0.02018038, -0.91007166, -0.76019922,
       -0.72942753,  0.79202314,  0.68922977,  0.21363167, -0.13315102,
        0.13932492,  0.90441536, -0.15937537, -0.72956232, -0.49318993,
       -0.74990533, -0.52426754,  0.62456638, -0.27716172, -0.97251127,
       -0.18653684, -0.02444109, -0.15955275, -0.11836623,  0.00908752,
        0.66084474,  0.0911753 ,  0.16174356, -0.37750537, -0.97674292,
        0.09016355, -0.96274921, -0.90136638,  0.31562259,  0.08972511,
       -0.58786755,  0.31203781,  0.69784146, -0.38635619, -0.96567208,
        0.06825108, -0.82099522,  0.26533379, -0.20634368, -0.57126868,
        0.90439878,  0.75456208, -0.425159  , -0.42676042, -0.59220951,
        0.98114764, -0.58532004, -0.56617453,  0.69781361,  0.1320131 ,
        0.28813971, -0.37250849,  0.72600734, -0.0610061 ,  0.95705977,
        0.07642949,  0.60841656,  0.54592347,  0.72867942, -0.85002505,
        0.44967138, -0.40752284, -0.98525709, -0.03762063,  0.35

In [2]:
import numpy as np 
#78. 考虑两组点集P0和P1去描述一组线(二维)和一个点p,如何计算点p到每一条线 i (P0[i],P1[i])的距离？(★★★)
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[ 5.2704922   5.19988554  0.39302378  1.40586523  1.21207801 13.95369216
 10.87267294  0.08666495  5.94860613 13.03608933]


In [3]:
# # based on distance function from previous question
#79.考虑两组点集P0和P1去描述一组线(二维)和一组点集P，如何计算每一个点 j(P[j]) 到每一条线 i (P0[i],P1[i])的距离？(★★★)
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.61236027  9.03421525  5.89612417 10.32524001  5.51791901  7.13178788
   1.94057181  6.30288014  7.5271265   7.47703214]
 [ 2.4242662  10.12109254  4.76749933  1.48479986  2.68628866  0.12144798
   8.24561998 12.20454894  4.08675704  4.83605747]
 [ 3.75876552  7.03302726  6.00942089  9.88743856  4.92281901  6.32358481
   4.03918357  4.04102353  9.34196259  8.56194958]
 [ 9.63859538  4.71399271  5.18076155  2.83371096  8.10577197  7.02197121
   6.24241405  4.01054375  8.110641    1.82084978]
 [ 5.86507164  7.71008941  8.04110446  1.96261527  6.14605277  3.56930789
   8.62696702 10.98261059  5.31877498  7.29987656]
 [13.19436594  1.42093145 14.25346546  8.96281872 13.29935695 10.87487392
   7.63624296  6.7694922   6.1998739  11.15369058]
 [ 6.88544713  4.22554233  1.61116046  0.35335712  5.06719544  4.21477197
   8.79959912  5.04407699 11.27379471  5.5339081 ]
 [ 4.63729646 11.01449889  4.62524902  9.76625891  5.17479347  7.09082656
   1.12484998  9.05187171  4.56963065  5.12208197]


In [8]:
#81. 考虑一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],如何生成一个数组R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]? (★★★)
Z = np.arange(1,15,dtype=np.uint32) 
#??? NameError: name 'stride_tricks' is not defined.原代码有点问题，需要改成：（加个：np.lib.）np.lib.stride_tricks.as_strided
R = np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [9]:
Z = np.random.uniform(0,1,(10,10)) #82. 计算一个矩阵的秩
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


In [12]:
#83. 如何找到一个数组中出现频率最高的值？
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

7


In [14]:
Z = np.random.randint(0,5,(10,10)) #84. 从一个10x10的矩阵中提取出连续的3x3区块(★★★)
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[3 0 2]
   [3 3 0]
   [2 1 4]]

  [[0 2 2]
   [3 0 1]
   [1 4 0]]

  [[2 2 1]
   [0 1 1]
   [4 0 3]]

  [[2 1 3]
   [1 1 3]
   [0 3 3]]

  [[1 3 1]
   [1 3 4]
   [3 3 0]]

  [[3 1 3]
   [3 4 1]
   [3 0 2]]

  [[1 3 1]
   [4 1 3]
   [0 2 1]]

  [[3 1 2]
   [1 3 1]
   [2 1 0]]]


 [[[3 3 0]
   [2 1 4]
   [4 0 4]]

  [[3 0 1]
   [1 4 0]
   [0 4 3]]

  [[0 1 1]
   [4 0 3]
   [4 3 4]]

  [[1 1 3]
   [0 3 3]
   [3 4 1]]

  [[1 3 4]
   [3 3 0]
   [4 1 3]]

  [[3 4 1]
   [3 0 2]
   [1 3 2]]

  [[4 1 3]
   [0 2 1]
   [3 2 0]]

  [[1 3 1]
   [2 1 0]
   [2 0 2]]]


 [[[2 1 4]
   [4 0 4]
   [1 3 2]]

  [[1 4 0]
   [0 4 3]
   [3 2 3]]

  [[4 0 3]
   [4 3 4]
   [2 3 0]]

  [[0 3 3]
   [3 4 1]
   [3 0 0]]

  [[3 3 0]
   [4 1 3]
   [0 0 4]]

  [[3 0 2]
   [1 3 2]
   [0 4 3]]

  [[0 2 1]
   [3 2 0]
   [4 3 0]]

  [[2 1 0]
   [2 0 2]
   [3 0 0]]]


 [[[4 0 4]
   [1 3 2]
   [1 4 3]]

  [[0 4 3]
   [3 2 3]
   [4 3 4]]

  [[4 3 4]
   [2 3 0]
   [3 4 4]]

  [[3 4 1]
   [3 0 0]
   [4 4 4]]

  [[4 1 3]
   

In [17]:
class Symetric(np.ndarray): #85. 创建一个满足 Z[i,j] == Z[j,i]的子类 (★★★) (提示: class 方法)
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 8  3  6  8 12]
 [ 3  0 10 11  7]
 [ 6 10  1 42  2]
 [ 8 11 42  9  2]
 [12  7  2  2  4]]


In [18]:
p, n = 10, 20 #86. 考虑p个 nxn 矩阵和一组形状为(n,1)的向量，如何直接计算p个矩阵的乘积(n,1)？(★★★)
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)
#It works, because:
#M is (p,n,n)
#V is (p,n,1)
#Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [19]:
Z = np.ones((16,16)) 
#87. 对于一个16x16的数组，如何得到一个区域(block-sum)的和(区域大小为4x4)? (★★★)
#(提示: np.add.reduceat)
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [23]:
def iterate(Z): #88. 如何利用numpy数组实现Game of Life? (★★★)
# Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

# Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [28]:
#89. 如何找到一个数组的第n个最大值? (★★★)
#(提示: np.argsort | np.argpartition)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# # 方法1
# # Slow
#print (Z[np.argsort(Z)[-n:]])

# # 方法2
# # Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9999 9996 9998 9997 9995]


In [29]:
#90. 给定任意个数向量，创建笛卡尔积(每一个元素的每一种组合)(★★★)
#(提示: np.indices)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [30]:
#91. 如何从一个正常数组创建记录数组(record array)? (★★★)
#(提示: np.core.records.fromarrays)
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print (R)


[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [36]:
#92. 考虑一个大向量Z, 用三种不同的方法计算它的立方(★★★)
#(提示: np.power, \*, np.einsum)
x = np.random.rand()
np.power(x,3)

## 方法2
# x*x*x

## 方法3 ???这个方法的代码有点问题！
#np.einsum('i,i,i->i',x,x,x)


0.00011313160622820567

In [37]:
#93. 考虑两个形状分别为(8,3) 和(2,2)的数组A和B. 如何在数组A中找到满足包含B中元素的行？(不考虑B中每行元素顺序)？ (★★★)
#(提示: np.where)
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[0 1 3 4 5 6]


In [39]:
#94. 考虑一个10x3的矩阵，分解出有不全相同值的行 (如 [2,2,3]) (★★★)
Z = np.random.randint(0,5,(10,3))
print (Z)

# # solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)

# # 方法2
# # soluiton for numerical arrays only, will work for any number of columns in Z
# U = Z[Z.max(axis=1) != Z.min(axis=1),:]
# print (U)

[[3 3 2]
 [0 0 4]
 [0 0 0]
 [4 4 3]
 [0 3 3]
 [3 0 0]
 [4 1 4]
 [1 3 0]
 [3 1 4]
 [4 4 4]]
[[3 3 2]
 [0 0 4]
 [4 4 3]
 [0 3 3]
 [3 0 0]
 [4 1 4]
 [1 3 0]
 [3 1 4]]


In [40]:
#95. 将一个整数向量转换为matrix binary的表现形式 (★★★)
#(提示: np.unpackbits)
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# # 方法2
# print (np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [41]:
#96. 给定一个二维数组，如何提取出唯一的(unique)行?(★★★)
#(提示: np.ascontiguousarray)

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 0 0]
 [0 1 0]
 [1 1 0]]


In [42]:
#97. 考虑两个向量A和B，写出用einsum等式对应的inner, outer, sum, mul函数(★★★)
#(提示: np.einsum)


A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))# np.sum(A)

print ('A * B')
print (np.einsum('i,i->i', A, B)) # A * B

print ('inner')
print (np.einsum('i,i', A, B))    # np.inner(A, B)

print ('outer')
print (np.einsum('i,j->ij', A, B))    # np.outer(A, B)

sum
4.311256815251577
A * B
[0.07087869 0.863815   0.06601426 0.35051391 0.00318295 0.06167924
 0.03139799 0.28402578 0.00933995 0.1303848 ]
inner
1.8712325809404302
outer
[[0.07087869 0.18511817 0.03031047 0.17589998 0.02265947 0.01615002
  0.00796585 0.07478632 0.05343391 0.15173359]
 [0.33074049 0.863815   0.14143744 0.82080022 0.10573565 0.07536066
  0.03717096 0.34897463 0.24933811 0.70803289]
 [0.15436924 0.4031755  0.06601426 0.38309885 0.04935087 0.0351737
  0.01734911 0.16287981 0.11637563 0.33046603]
 [0.14123917 0.36888291 0.06039934 0.35051391 0.04515327 0.03218196
  0.01587346 0.14902586 0.10647716 0.30235783]
 [0.00995624 0.02600332 0.00425767 0.02470845 0.00318295 0.00226857
  0.00111895 0.01050514 0.0075058  0.02131383]
 [0.27069592 0.70699295 0.11576006 0.67178732 0.08653978 0.06167924
  0.03042273 0.28561972 0.2040718  0.57949243]
 [0.27937364 0.72965708 0.11947099 0.69332286 0.08931399 0.0636565
  0.03139799 0.29477586 0.21061375 0.59806927]
 [0.26918525 0.70304746 0

In [44]:
#98. 考虑一个由两个向量描述的路径(X,Y)，如何用等距样例(equidistant samples)对其进行采样(sample)? (★★★)
#Considering a path described by two vectors (X,Y), how to sample it using equidistant samples
#(提示: np.cumsum, np.interp)


phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [45]:
#99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
#(提示: np.logical_and.reduce, np.mod)

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]


In [46]:
#100. 对于一个一维数组X，计算它boostrapped之后的95%置信区间的平均值。
#(Compute bootstrapped 95% confidence intervals for the mean of a 1D array X，i.e. resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
#(提示: np.percentile)

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.11427887  0.26301195]
