# 一、pandas中数据结构介绍
# Series 

In [9]:
from pandas import Series, DataFrame

In [10]:
import pandas as pd

In [11]:
obj = Series([4, 7, -5, 3])

In [12]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [13]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [14]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [15]:
obj2 = Series([4, 7, -5, 3], index = ['a', 'b', 'c', 'd'])

In [12]:
obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [13]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [16]:
obj2['c']

-5

In [17]:
obj2['d'] = 6

In [18]:
obj2[['b', 'c','d']]

b    7
c   -5
d    6
dtype: int64

In [19]:
obj2

a    4
b    7
c   -5
d    6
dtype: int64

In [20]:
obj2[obj2>0]

a    4
b    7
d    6
dtype: int64

In [21]:
obj2 * 2

a     8
b    14
c   -10
d    12
dtype: int64

In [23]:
import numpy as np
np.exp(obj2)

a      54.598150
b    1096.633158
c       0.006738
d     403.428793
dtype: float64

In [25]:
'b' in obj2

True

In [28]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [29]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [31]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [32]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [33]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [34]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [35]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [36]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [37]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

# DataFrame

In [41]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2003, 2004],
        'pop': [1.5, 1.7, 3.7, 2.4, 2.9]}
frame = DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.7
3  Nevada  2003  2.4
4  Nevada  2004  2.9

In [42]:
DataFrame(data, columns = ['year', 'state', 'pop']) 

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.7
3  2003  Nevada  2.4
4  2004  Nevada  2.9

In [43]:
frame2 = DataFrame(data, columns = ['year', 'state', 'pop', 'debt'],
                   index = ['one', 'two', 'three', 'four', 'five']) 
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.7  NaN
four   2003  Nevada  2.4  NaN
five   2004  Nevada  2.9  NaN

In [44]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [45]:
frame['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
Name: state, dtype: object

In [46]:
frame2.year

one      2000
two      2001
three    2002
four     2003
five     2004
Name: year, dtype: int64

In [47]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [49]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.7
debt      NaN
Name: three, dtype: object

In [50]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.7  16.5
four   2003  Nevada  2.4  16.5
five   2004  Nevada  2.9  16.5

In [51]:
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.7   2.0
four   2003  Nevada  2.4   3.0
five   2004  Nevada  2.9   4.0

In [52]:
val = Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.7   NaN
four   2003  Nevada  2.4  -1.5
five   2004  Nevada  2.9  -1.7

In [53]:
frame2['eastern'] = frame2.state =='Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.7   NaN     True
four   2003  Nevada  2.4  -1.5    False
five   2004  Nevada  2.9  -1.7    False

In [55]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [57]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [58]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [59]:
DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [61]:
pdata = {'Ohio': frame3['Ohio'][:-1],     #逗号经常容易忘记加！
         'Nevada': frame3['Nevada'][:2]}
DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [62]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [63]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [64]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.7, nan],
       [2003, 'Nevada', 2.4, -1.5],
       [2004, 'Nevada', 2.9, -1.7]], dtype=object)

# 索引对象

In [65]:
obj = Series(range(3), index = ['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [66]:
index[1:]

Index(['b', 'c'], dtype='object')

In [67]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [69]:
'Ohio' in frame3.columns

True

In [70]:
2003 in frame3.index

False

# 二、基本功能
# 重新索引

In [71]:
obj = Series([4.5,7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [72]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [74]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value = 0) #这里是fill_value，不是fill_values。

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [76]:
obj3 = Series(['blue', 'purple', 'yellow'], index = [0, 2, 4])
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

# 丢弃指定轴上的项

In [77]:
obj = Series(np.arange(5.), index = ['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [78]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [80]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [81]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [82]:
data.drop('two', axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [83]:
data.drop(['two', 'four'],axis = 1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

# 索引、选取和过滤

In [86]:
obj = Series(np.arange(4.), index = ['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [87]:
obj['b']

1.0

In [88]:
obj[1]

1.0

In [89]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [91]:
obj[['b', 'a', 'd']] #几个索引时用两个括号！

b    1.0
a    0.0
d    3.0
dtype: float64

In [92]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [93]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [94]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [95]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [96]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [97]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [98]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [99]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [100]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [102]:
data[data<5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [104]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [8]:
data.ix[['Colorado','Utah'],[3, 0, 1]]

NameError: name 'data' is not defined

In [113]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

# 算术运算和数据对齐

In [114]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index = ['a', 'c', 'd', 'e'])
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a', 'c', 'e', 'f', 'g'])

In [115]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [116]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [117]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [119]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [120]:
arr[0]

array([0., 1., 2., 3.])

In [121]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [124]:
frame = DataFrame(np.arange(12.).reshape((4,3)), columns = list('bde'),
                  index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [125]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [126]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [129]:
series2 = Series(range(3), index=['b', 'e', 'f'])
frame +series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [131]:
series3 = frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [133]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [134]:
frame.sub(series3, axis = 0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

# 函数应用和映射

In [136]:
frame = DataFrame(np.random.randn(4,3),columns = list('bde'),
                  index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -1.022172 -1.509157 -0.078384
Ohio    0.538348 -1.080351  0.935798
Texas  -0.802129  0.348990 -0.068553
Oregon -0.724112  0.002607 -0.034168

In [137]:
np.abs(frame)

b         d         e
Utah    1.022172  1.509157  0.078384
Ohio    0.538348  1.080351  0.935798
Texas   0.802129  0.348990  0.068553
Oregon  0.724112  0.002607  0.034168

In [138]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.560520
d    1.858147
e    1.014182
dtype: float64

In [139]:
frame.apply(f,axis = 1)

Utah      1.430773
Ohio      2.016149
Texas     1.151119
Oregon    0.726719
dtype: float64

# 排序和排名

In [140]:
obj = Series(range(4), index = ['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [141]:
frame = DataFrame(np.arange(8).reshape((2,4)), index = ['three', 'one'],
                  columns = ['d', 'a', 'b', 'c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [142]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [143]:
frame.sort_index(axis=1, ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [145]:
obj = Series([4, 7, -3, 2]) 
obj.sort_values() #Seris对象没有order属性的意思，然后我百度是没有了一下，说是Python3.6之后的版本已经没有order属性了，尝试使用sort_values()方法就好了。

2   -3
3    2
0    4
1    7
dtype: int64

In [146]:
obj = Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [147]:
frame = DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [149]:
frame.sort_values(by = 'b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [150]:
frame.sort_values(by = ['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [152]:
obj = Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [153]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [154]:
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [155]:
obj.rank(ascending = False, method = 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

# 带有重复值的轴索引

In [157]:
obj = Series(range(5), index = ['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [159]:
obj.index.is_unique

False

In [160]:
obj['a']

a    0
a    1
dtype: int64

# 汇总和计算描述统计

In [164]:
df = DataFrame([[1.4, np.nan], [7.1, -4.5], #这两行要用括号括起来！
               [np.nan, np.nan], [0.75, -1.3]],
               index = ['a', 'b', 'c', 'd'],
               columns = ['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [165]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [166]:
df.sum(axis = 1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [167]:
df.mean(axis = 1, skipna = False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [168]:
df.idxmax()

one    b
two    d
dtype: object

In [171]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [172]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

# 相关系数与协方差

In [22]:
import datetime
import pandas_datareader.data as web
all_data = {}
for ticker in [ 'IBM', 'MSFT', 'GOOG']:
    all_data[ticker] = web.get_data_famafrench(ticker, '1/1/2000', '1/1/2010')
    
price = DataFrame({tic: data['Adj Close']
                       for tic, data in all_data.items()}) #Python3.5中：iteritems变为items!
volumn = DataFrame({tic: data['Volumn']
                       for tic, data in all_data.items()})

RemoteDataError: Unable to read URL: http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/IBM_CSV.zip
Response Text:
b'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>\r\n<title>404 - File or directory not found.</title>\r\n<style type="text/css">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}\r\n-->\r\n</style>\r\n</head>\r\n<body>\r\n<div id="header"><h1>Server Error</h1></div>\r\n<div id="content">\r\n <div class="content-container"><fieldset>\r\n  <h2>404 - File or directory not found.</h2>\r\n  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n</html>\r\n'

# 唯一值、值计数以及成员资格

In [187]:
obj = Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [188]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [189]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [190]:
pd.value_counts(obj.values, sort = False)

c    3
a    3
b    2
d    1
dtype: int64

In [191]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [192]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [193]:
data = DataFrame({'Qu1': [1,3,4,3,4],
                  'Qu2': [2,3,1,2,3],
                  'Qu3': [1,5,2,4,4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [194]:
result = data.apply(pd.value_counts).fillna(0)

In [195]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

# 处理缺失数据

In [256]:
import numpy as np #？？这里为什么NaN没有被当成缺失数据处理？
string_data = Series(['aardvark', 'artichoke', 'np.nan', 'avocado'])
string_data

0     aardvark
1    artichoke
2       np.nan
3      avocado
dtype: object

In [257]:
string_data.isnull()

0    False
1    False
2    False
3    False
dtype: bool

In [213]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2    False
3    False
dtype: bool

# 滤除缺失数据

In [215]:
from numpy import nan as NA

In [216]:
data = Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [217]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [221]:
data = DataFrame([[1., 6.5, 3.], [1.,NA, NA], #不要少写了括号！有两对括号。
                 [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna()
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [222]:
data.dropna(how = 'all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [225]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [227]:
data.dropna(axis = 1, how = 'all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [231]:
df = DataFrame(np.random.randn(7,3))
df.iloc[:4, 1] = NA; df.iloc[:2, 2] = NA
df

0         1         2
0  0.499958       NaN       NaN
1  0.758753       NaN       NaN
2 -1.014497       NaN -0.640847
3 -2.086840       NaN  1.343669
4 -0.379165 -1.132967  2.108534
5  1.008802  0.798974 -1.161112
6  0.611633 -0.354366 -1.179008

# 填充缺失数据

In [232]:
df.dropna(thresh = 3)

0         1         2
4 -0.379165 -1.132967  2.108534
5  1.008802  0.798974 -1.161112
6  0.611633 -0.354366 -1.179008

In [233]:
df.fillna(0)

0         1         2
0  0.499958  0.000000  0.000000
1  0.758753  0.000000  0.000000
2 -1.014497  0.000000 -0.640847
3 -2.086840  0.000000  1.343669
4 -0.379165 -1.132967  2.108534
5  1.008802  0.798974 -1.161112
6  0.611633 -0.354366 -1.179008

In [238]:
df.fillna({1:0.5, 3:-1})

0         1         2
0  0.499958  0.000000  0.000000
1  0.758753  0.000000  0.000000
2 -1.014497  0.000000 -0.640847
3 -2.086840  0.000000  1.343669
4 -0.379165 -1.132967  2.108534
5  1.008802  0.798974 -1.161112
6  0.611633 -0.354366 -1.179008

In [237]:
_ = df.fillna(0, inplace=True)
df

0         1         2
0  0.499958  0.000000  0.000000
1  0.758753  0.000000  0.000000
2 -1.014497  0.000000 -0.640847
3 -2.086840  0.000000  1.343669
4 -0.379165 -1.132967  2.108534
5  1.008802  0.798974 -1.161112
6  0.611633 -0.354366 -1.179008

# 层次化索引

In [239]:
data = Series(np.random.randn(10),
              index = [['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'],
                       [1, 2, 3, 1, 2, 3, 1, 2, 2, 3]])
data

a  1    0.944362
   2    2.991646
   3   -0.031361
b  1   -0.898519
   2   -0.028454
   3   -0.986764
c  1    0.557522
   2    2.042498
d  2   -0.274922
   3   -2.590035
dtype: float64

In [241]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           codes=[[0, 0, 0, 1, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 1, 2]])

In [242]:
data['b']

1   -0.898519
2   -0.028454
3   -0.986764
dtype: float64

In [243]:
data['b': 'c']

b  1   -0.898519
   2   -0.028454
   3   -0.986764
c  1    0.557522
   2    2.042498
dtype: float64

In [244]:
data.loc[['b', 'd']]

b  1   -0.898519
   2   -0.028454
   3   -0.986764
d  2   -0.274922
   3   -2.590035
dtype: float64

In [245]:
data[:, 2]

a    2.991646
b   -0.028454
c    2.042498
d   -0.274922
dtype: float64

In [246]:
data.unstack()

1         2         3
a  0.944362  2.991646 -0.031361
b -0.898519 -0.028454 -0.986764
c  0.557522  2.042498       NaN
d       NaN -0.274922 -2.590035

In [247]:
data.unstack().stack()

a  1    0.944362
   2    2.991646
   3   -0.031361
b  1   -0.898519
   2   -0.028454
   3   -0.986764
c  1    0.557522
   2    2.042498
d  2   -0.274922
   3   -2.590035
dtype: float64

# 使用DataFrame的列

In [248]:
frame = DataFrame({'a': range(7), 'b': range(7, 0, -1),
                   'c': ['one', 'one', 'one', 'two', 'two', 'two', 'two'],
                   'd': [0, 1, 2, 0, 1, 2, 3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [249]:
frame2 = frame.set_index(['c', 'd'])
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [250]:
frame.set_index(['c', 'd'], drop = False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [251]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1